name: ci

on: push

env:
  FOUNDRY_PROFILE: ci

jobs:
  ci:
    name: Build code and run tests
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    timeout-minutes: 15
    container:
      image: ghcr.io/pixel8xyz/contracts-builder:latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - run: echo "/root/.cargo/bin:/root/.foundry/bin:/root/.bun/bin" >> $GITHUB_PATH
      - run: svm install 0.8.24 && svm use 0.8.24
      #Â disable safe.directory system to avoid forge install error
      - run: git config --global --add safe.directory '*' 
      # install deps
      - run: forge install
      - run: bun i
      - run: bun compile
      - run: bun tests-coverage

      - name: Upload coverage report to Coveralls
        uses: coverallsapp/github-action@v2        
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

